SET ROLE aether_identity_owner;

DROP SCHEMA IF EXISTS identity CASCADE;
DROP SCHEMA IF EXISTS authz CASCADE;
DROP SCHEMA IF EXISTS app CASCADE;
DROP EXTENSION IF EXISTS pgcrypto;
DROP SCHEMA IF EXISTS extensions CASCADE;

RESET ROLE;
