apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aether-judge-control
helmGlobals:
  chartHome: ../../../helm/charts
helmCharts:
  - name: judge-control
    releaseName: aether
    namespace: aether-judge-control
    valuesFile: values.yaml
